---
driver:
  name: azurerm

driver_config:
  subscription_id: '09f2ee05-2cb0-4996-a24e-b4d3083b0cbd'
  location: 'southcentralus'
  machine_size: 'Standard_D1'

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: windows2012-r2
    driver_config:
      image_urn: MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:latest
    transport:
      name: winrm
suites:
  - name: default
    run_list:
      - recipe[workstation::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
